apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: heartbeat-source
  namespace: demo-test
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-nightly/knative.dev/eventing/cmd/heartbeats:latest
          name: heartbeats
          env:
            - name: POD_NAME
              value: "mypod"
            - name: POD_NAMESPACE
              value: "demo-test"
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
