apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: pingsource-test
  namespace: demo-test
spec:
  schedule: "* * * * *"
  contentType: "application/json"
  data: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
