apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
  nammspace: sinkbinding-example
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
