apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: sinkbinding-test
  namespace: sinkbinding-example
spec:
  subject:
    apiVersion: batch/v1
    kind: CronJobJob
    selector:
      matchLabels:
        app: heartbeat-cron
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
